Serving Size 1 Packet: 2.0
Servings Per Container: 30
# daily_value_append:
#   '*: Percent Daily Values are based on a 2,000 calorie diet.
#   '**': Daily Value not established.
functions:
  Anti-Aging:
      basic:
        Calories:
          Amount Per Serving: 3.76
        Total Carbohydrate:
          Amount Per Serving: 1.78
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.65
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Superoxide Dismutase (SOD):
          Amount Per Serving: 10
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Beauty:
      basic:
        Calories:
          Amount Per Serving: 5.98
        Total Carbohydrate:
          Amount Per Serving: 0.69
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 0.56
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Protein:
          Amount Per Serving: 1
          unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Hydrolyzed Collagen:
          Amount Per Serving: 1000
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Brain Care:
      basic:
        Calories:
          Amount Per Serving: 3.29
        Total Carbohydrate:
          Amount Per Serving: 1.56
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.48
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Citicoline:
          Amount Per Serving: 250
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Digestive Care:
      basic:
        Calories:
          Amount Per Serving: 3.65
        Total Carbohydrate:
          Amount Per Serving: 1.73
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.60
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Ganeden BC30 (Bacillus coagulans):
          Amount Per Serving: 67
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Eye Care:
      basic:
        Calories:
          Amount Per Serving: 3.54
        Total Carbohydrate:
          Amount Per Serving: 1.67
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.54
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Lutein & Zeaxanthine Lutemax 20/20:
          Amount Per Serving: 6
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Heart Care:
      basic:
        Calories:
          Amount Per Serving: 3.53
        Total Carbohydrate:
          Amount Per Serving: 1.67
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.53
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Coenzyme Q10:
          Amount Per Serving: 50
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Immune Care:
      basic:
        Calories:
          Amount Per Serving: 3.42
        Total Carbohydrate:
          Amount Per Serving: 1.61
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.48
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Beta 1,3D Glucan Complex:
          Amount Per Serving: 200
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Joint Care:
      basic:
        Calories:
          Amount Per Serving: 0.81
        Total Carbohydrate:
          Amount Per Serving: 0.31
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 0.17
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Glucosamine Hydrochloride Green Grown:
          Amount Per Serving: 1500
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Liver Care:
      basic:
        Calories:
          Amount Per Serving: 2.99
        Total Carbohydrate:
          Amount Per Serving: 1.41
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.32
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Milk Thistle PE (Seed)(Sylibum marianum):
          Amount Per Serving: 200
          unit: mg
          daily_value_append: '**'
        Artichoke PE (Leaf)(Cynara scolymus):
          Amount Per Serving: 200
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Men's Vitality:
      basic:
        Calories:
          Amount Per Serving: 3.56
        Total Carbohydrate:
          Amount Per Serving: 1.70
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.61
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Tongkat Ali (Root)(Eurycoma Longifolia):
          Amount Per Serving: 100
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Sleep Support:
      basic:
        Calories:
          Amount Per Serving: 5
        Total Carbohydrate:
          Amount Per Serving: 2
          unit: g
          '% Daily Value': 1
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 2
              unit: g
              '% Daily Value': 7
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        Melatonin:
          Amount Per Serving: 6
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
  Stress Management:
      basic:
        Calories:
          Amount Per Serving: 3.59
        Total Carbohydrate:
          Amount Per Serving: 1.70
          unit: g
          daily_value_append: '*'
          carbohydrate:
            Dietary Fiber:
              Amount Per Serving: 1.56
              unit: g
              daily_value_append: '*'
            Sugars:
              Amount Per Serving: 0
              unit: g
        Sodium:
          Amount Per Serving: 0
          unit: mg
          '% Daily Value': 0
      extra:
        L-Theanine:
          Amount Per Serving: 100
          unit: mg
          daily_value_append: '**'
      Other Ingredients: Non GMO Soluble Corn Fiber, Natural Flavors, Citric Acid, Monk Fruit Concentrate.
