#!/usr/bin/expect
set timeout 1000000
spawn ./dbinit
while 1 {
  expect {
    "\\\[Ynaqdh\\\] $" {
      send "a\r"
    }

    "\\\[Y/n\\\] $" {
      send "\r"
    }

    "Email \\\[spree@example.com\\\]: $" {
      send "1@1.com\r"
    }

    "Password \\\[spree123\\\]: $" {
      send "111111\r"
    }

    eof {
      exit
    }
  }

}
